In [1]:
from pso import PSO
from pso.initializers import UniformInitializer
from pso.topology import GlobalTopology, LocalTopology, FocalTopology
from test_functions import sphereFunction, rastriginsFunction, rosenbrockFunction

In [2]:
num_particles = 30
num_dimensions = 30
num_iterations = 10000
c1 = c2 = 2.05

In [3]:
basicPSO = PSO(
    num_particles=num_particles,
    num_dims=num_dimensions,
    c1=c1,
    c2=c2,
    topology=GlobalTopology(),
)

In [4]:
basicPSO.initialize(UniformInitializer([[-5.12, 5.12]]))
for i in range(num_iterations):
    basicPSO.minimize(sphereFunction)

/home/aldo/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/home/aldo/git/swarm-intelligence/test_functions.py:6: RuntimeWarning: overflow encountered in square
  return np.sum(x**2)
/home/aldo/git/swarm-intelligence/pso/pso.py:54: RuntimeWarning: overflow encountered in add
  self.vel = self._get_w()*self.vel + self.c1*r1*(self.pbest - self.pos) + self.c2*r2*(lbest - self.pos)
/home/aldo/git/swarm-intelligence/pso/pso.py:54: RuntimeWarning: invalid value encountered in add
  self.vel = self._get_w()*self.vel + self.c1*r1*(self.pbest - self.pos) + self.c2*r2*(lbest - self.pos)
/home/aldo/git/swarm-intelligence/pso/pso.py:55: RuntimeWarning: overflow encountered in add
  self.pos = self.pos + self.clerc_factor*self.vel
/home/aldo/git/swarm-intelligence/pso/pso.py:45: RuntimeWarning: invalid value encountered in less
  better = fitness < self.pbest_fitness
/home/a

In [5]:
basicPSO.getBestSolution()

(array([ 1.03992333, -0.53156967, -1.47843806, -0.68027118,  0.22832396,
         0.72758097,  0.27830997,  0.27056125,  0.47653327, -0.85901047,
         0.21263951, -2.15029594,  0.83241257,  2.00981313,  0.62048598,
         0.0386832 , -0.62576882,  2.18466271,  0.14769127, -0.61111625,
        -0.01823707,  1.57255005,  1.94898138, -0.09547981, -0.06901906,
         2.45373471,  0.83135196, -0.54095509, -0.22651683,  0.40020715]),
 array([34.55878683]))

In [4]:
import numpy as np

In [72]:
basicPSO.initialize(UniformInitializer([[-5.12, 5.12]]))

In [93]:
basicPSO.minimize(sphereFunction)
basicPSO.getBestSolution()

(array([-0.3347569 , -1.16583764, -0.19577141, -0.72160066, -0.24592559,
         0.17725647, -0.78827835,  0.77215564, -0.41833093, -0.89073865,
         0.63773355, -0.94201724, -0.08108438, -0.16902725, -0.1942792 ,
        -0.21888255, -0.21303247,  0.38712461, -0.51237199, -0.63868265,
         0.49710535, -1.79566752,  0.11561685,  0.91832044,  0.6476765 ,
         1.1252929 ,  0.25453281, -1.19972273, -0.88014683, -1.42689801]),
 array([16.91758648]))

In [14]:
r1, r2 = [np.random.uniform(0, 1, 5)[:, None] for _ in range(2)]

In [17]:
r1

array([[0.74706745],
       [0.17220533],
       [0.00861539],
       [0.63987541],
       [0.89245061]])

In [8]:
import numpy as np

In [15]:
l = np.array([1,2,3])[:, None]

In [17]:
np.logical_and(l,l)

array([[ True],
       [ True],
       [ True]])

In [56]:
np.where(np.array([True, False])[:,None], [[1,2], [3,4]], [[10,20],[30,40]])

array([[ 1,  2],
       [30, 40]])

In [18]:
gt = GlobalTopology()

In [24]:
pbest = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [32]:
pbest[FocalTopology()(np.array([10,2,3])[:, None])]

array([[4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])